// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Configuration, ConfigurationData } from "./tables/Configuration.sol";
import { VerifierAddress } from "./tables/VerifierAddress.sol";
import { PlayerGame, PlayerGameData } from "./tables/PlayerGame.sol";
import { GamePlayer } from "./tables/GamePlayer.sol";
import { Map } from "./tables/Map.sol";
import { PendingGame } from "./tables/PendingGame.sol";
import { PendingDig, PendingDigData } from "./tables/PendingDig.sol";
